### ISSUE TITLE
Serial port pinout

### ISSUE THREAD

**Issue by itimees** [sgayou/subaru-starlink-research#3]
First off thanks for the nice write-up AND the photos taken 👍 
Could you also add the serial port pinout on the connector, please?!
(or perhaps just confirm if they more or less match the photo or if the photo is there just for illustrative purposes :)

**Comment by itimees** [comment]
Ok, I can confirm on another Harman board (VP4) serial pins are likewise exactly in the middle of one of the same type 2x5 connectors as pictured ;)

**Comment by sgayou** [comment]
Good luck! Please write up anything you find.
